# Generated by Django 5.0.6 on 2024-07-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_project_description_project_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='attached_documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='project',
            name='geography',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
