# Generated by Django 5.0.6 on 2024-07-10 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_projectdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='attached_documents',
        ),
    ]
