# Generated by Django 5.0.6 on 2024-07-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_project_attached_documents_delete_projectdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='service_scope',
            field=models.TextField(blank=True, null=True),
        ),
    ]
