# Generated by Django 5.0.6 on 2024-07-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_delete_user_alter_customuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter phone number', max_length=20, null=True, unique=True),
        ),
    ]
