# Generated by Django 4.2.14 on 2024-07-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_projectlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='geographies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='requirements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='service_scope',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
