# Generated by Django 4.2.14 on 2024-07-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_project_geographies_alter_project_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='geographies',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='service_scope',
            field=models.TextField(blank=True, null=True),
        ),
    ]
